spring:
  datasource:
    url: jdbc:log4jdbc:mysql://197.214.8.128:3306/ailsdb?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: ails
    password: "!new1234"

file:
  basedir: /home/ails/project/upload
  chunkSize: 1048576


